[package]
name = "worker-route-example"
version = "0.0.1"
publish = false
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.0.18"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
worker-route = { path = "../" }
