[package]
name = "worker-route"
version = "0.0.1"
edition = "2021"

[dependencies]
worker = "0.0.18"
serde = { version = "1.0.187", features = ["derive"] }
serde_json = "1.0.105"
serde_qs = "0.12.0"
worker-macro = { path = "macro" }

[workspace]
members = ["macro", "example"]
